In [57]:
import numpy as np
import nibabel as nib
import math
import datetime
import os
from multiprocessing import Pool

In [32]:
fileRHUH = nib.load('prob_dist_results/RHUH_DATASET/probdist_RHUH_whole_tumor.nii')
imgRHUH = fileRHUH.get_fdata()
fileBTP = nib.load('prob_dist_results/BRAIN-TUMOR-PROGRESSION_DATASET/probdist_BTP_whole_tumor.nii')
imgBTP = fileBTP.get_fdata()


In [ ]:
# Iterate over every voxel


def fisher():
    result_array = np.zeros_like(imgRHUH, dtype=float)

    for (x_RHUH,y_RHUH,z_RHUH), valueRHUH in np.ndenumerate(imgRHUH):
        valueBTP = imgBTP[x_RHUH, y_RHUH, z_RHUH]
        a = int(valueRHUH)
        b = int(valueBTP)
        c = 39 - a
        d = 20 - b
        n = 59
         
        p = ((math.factorial(a + b)) * (math.factorial(c + d)) * (math.factorial(a + c)) * (math.factorial(b + d))) / ((math.factorial(a)) * (math.factorial(b)) * (math.factorial(c)) * (math.factorial(d)) * (math.factorial(n)))

        result_array[x_RHUH, y_RHUH, z_RHUH] = p
    
    return result_array

start = time.time()
result_array = fisher()
end = time.time()

print("Time elapsed: ", end - start)



In [66]:
x = imgRHUH.flatten()

def fisher_fast(x):
    result_array = np.zeros_like(imgRHUH, dtype=float)

    shape = result_array.shape

    y = imgBTP.flatten()
    z = result_array.flatten()

    for i, value in enumerate(x):
        a = int(value)
        b = int(y[i])
        c = 39 - a
        d = 20 - b
        n = 59
         
        p = ((math.factorial(a + b)) * (math.factorial(c + d)) * (math.factorial(a + c)) * (math.factorial(b + d))) / ((math.factorial(a)) * (math.factorial(b)) * (math.factorial(c)) * (math.factorial(d)) * (math.factorial(n)))

        z[i] = p

    result_array = z.reshape(shape)
    
    return result_array


result_array = fisher_fast()

range(0, 8928000)


In [67]:
# Retain only p values of less than 0.05

mask = result_array < 0.01

filtered_array = np.zeros_like(result_array)
filtered_array[mask] = result_array[mask]

filtered_array = np.nan_to_num(filtered_array)





In [68]:
# Save the result
img = nib.Nifti1Image(filtered_array, affine=fileBTP.affine)
nib.save(img, 'prob_dist_results/combined_prob_dist.nii')

In [24]:
result_array = np.zeros_like(imgRHUH, dtype=float)


result_array_test = np.zeros_like(array1, dtype=float)

array1 = [[[1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]],
 
 [[10, 11, 12],
  [13, 14, 15],
  [16, 17, 18]],
 
 [[19, 20, 21],
  [22, 23, 24],
  [25, 26, 27]]]

array2 = [[[27, 26, 25],
  [24, 23, 22],
  [21, 20, 19]],
 
 [[18, 17, 16],
  [15, 14, 13],
  [12, 11, 10]],
 
 [[9, 8, 7],
  [6, 5, 4],
  [3, 2, 1]]]

for (x,y,z), value1 in np.ndenumerate(array1):
    value2 = array2[x,y,z]
    result_array_test[x,y,z] = value1 + value2

TypeError: list indices must be integers or slices, not tuple

In [23]:
print(result_array_test)

[[[28. 28. 28.]
  [28. 28. 28.]
  [28. 28. 28.]]

 [[28. 28. 28.]
  [28. 28. 28.]
  [28. 28. 28.]]

 [[28. 28. 28.]
  [28. 28. 28.]
  [28. 28. 28.]]]
